### ISSUE TITLE
502 bad gateway error

### ISSUE THREAD

**Issue by mcortes19** [chirripo/chirripo#42]
## Issue Type

 - Bug Report / Support Request

### php -v

```
7.4.12
```

### docker --version

```
2.5.0.1 docker desktop
```

## Your OS

 - **macOS** (Big Sur)

## Summary

In Drupal sites, we're getting the 502 bad gateway error: <img width="1467" alt="Screen Shot 2020-12-10 at 09 24 45" src="https://user-images.githubusercontent.com/11282049/101791792-8dfdf380-3ac9-11eb-9e9b-749b55c96a2a.png">

To solve that, we need to add the following fastcgi settings in the `docker/nginx/default.conf.template` file:

```
fastcgi_buffers 16 16k;
fastcgi_buffer_size 32k;
```

**Comment by kporras07** [comment]
@mcortes19 could you give it a try to the linked PR? Please

**Comment by rigoucr** [comment]
Fixed and merged
